from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (
    AboutView,
    AddToCartView,
    BrandCreateView,
    BrandDeleteView,
    BrandDetailView,
    BrandListView,
    BrandUpdateView,
    CartView,
    CategoryCreateView,
    CategoryDeleteView,
    CategoryDetailView,
    CategoryListView,
    CategoryUpdateView,
    ClubCreateView,
    ClubDeleteView,
    ClubDetailView,
    ClubListView,
    ClubUpdateView,
    CreateOrderFromCartView,
    HomeView,
    OrderDetailView,
    OrderListView,
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
    ProductUpdateView,
    RegisterView,
    RemoveFromCartView,
    SupplierCreateView,
    SupplierDeleteView,
    SupplierDetailView,
    SupplierListView,
    SupplierUpdateView,
    UpdateCartItemView,
)

app_name = "shop"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("cart/", CartView.as_view(), name="cart"),
    path(
        "cart/add/<slug:slug>/",
        AddToCartView.as_view(),
        name="cart_add",
    ),
    path(
        "cart/update/<int:pk>/",
        UpdateCartItemView.as_view(),
        name="cart_update",
    ),
    path(
        "cart/remove/<int:pk>/",
        RemoveFromCartView.as_view(),
        name="cart_remove",
    ),
    path(
        "cart/create-order/",
        CreateOrderFromCartView.as_view(),
        name="cart_create_order",
    ),
    path(
        "login/",
        LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("products/", ProductListView.as_view(), name="product_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path(
        "products/<slug:slug>/edit/",
        ProductUpdateView.as_view(),
        name="product_update",
    ),
    path(
        "products/<slug:slug>/delete/",
        ProductDeleteView.as_view(),
        name="product_delete",
    ),
    path("products/<slug:slug>/", ProductDetailView.as_view(), name="product_detail"),
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path(
        "categories/create/",
        CategoryCreateView.as_view(),
        name="category_create",
    ),
    path(
        "categories/<slug:slug>/edit/",
        CategoryUpdateView.as_view(),
        name="category_update",
    ),
    path(
        "categories/<slug:slug>/delete/",
        CategoryDeleteView.as_view(),
        name="category_delete",
    ),
    path(
        "categories/<slug:slug>/",
        CategoryDetailView.as_view(),
        name="category_detail",
    ),
    path("clubs/", ClubListView.as_view(), name="club_list"),
    path("clubs/create/", ClubCreateView.as_view(), name="club_create"),
    path("clubs/<int:pk>/edit/", ClubUpdateView.as_view(), name="club_update"),
    path("clubs/<int:pk>/delete/", ClubDeleteView.as_view(), name="club_delete"),
    path("clubs/<int:pk>/", ClubDetailView.as_view(), name="club_detail"),
    path("brands/", BrandListView.as_view(), name="brand_list"),
    path("brands/create/", BrandCreateView.as_view(), name="brand_create"),
    path("brands/<int:pk>/edit/", BrandUpdateView.as_view(), name="brand_update"),
    path("brands/<int:pk>/delete/", BrandDeleteView.as_view(), name="brand_delete"),
    path("brands/<int:pk>/", BrandDetailView.as_view(), name="brand_detail"),
    path("suppliers/", SupplierListView.as_view(), name="supplier_list"),
    path("suppliers/create/", SupplierCreateView.as_view(), name="supplier_create"),
    path(
        "suppliers/<int:pk>/edit/",
        SupplierUpdateView.as_view(),
        name="supplier_update",
    ),
    path(
        "suppliers/<int:pk>/delete/",
        SupplierDeleteView.as_view(),
        name="supplier_delete",
    ),
    path("suppliers/<int:pk>/", SupplierDetailView.as_view(), name="supplier_detail"),
    path("orders/", OrderListView.as_view(), name="order_list"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_detail"),
]
