BEGIN;

CREATE TABLE "firstproject_brand" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(120) NOT NULL,
    "country" varchar(80) NOT NULL,
    "logo" varchar(180) NOT NULL,
    "description" text NOT NULL
);

CREATE TABLE "firstproject_category" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(120) NOT NULL,
    "slug" varchar(50) NOT NULL UNIQUE,
    "description" text NOT NULL
);

CREATE TABLE "firstproject_club" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(120) NOT NULL,
    "country" varchar(80) NOT NULL,
    "league" varchar(120) NOT NULL,
    "logo" varchar(180) NOT NULL,
    "description" text NOT NULL
);

CREATE TABLE "firstproject_customer" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "first_name" varchar(80) NOT NULL,
    "last_name" varchar(80) NOT NULL,
    "email" varchar(254) NOT NULL UNIQUE,
    "phone" varchar(30) NOT NULL
);

CREATE TABLE "firstproject_supplier" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(140) NOT NULL,
    "city" varchar(100) NOT NULL,
    "email" varchar(254) NOT NULL,
    "phone" varchar(30) NOT NULL,
    "description" text NOT NULL
);

CREATE TABLE "firstproject_order" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL,
    "status" varchar(20) NOT NULL,
    "delivery_address" varchar(240) NOT NULL,
    "customer_id" bigint NOT NULL,
    "user_id" integer NULL
);

CREATE TABLE "firstproject_product" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(160) NOT NULL,
    "slug" varchar(50) NOT NULL UNIQUE,
    "price" numeric(10, 2) NOT NULL,
    "stock" integer NOT NULL CHECK ("stock" >= 0),
    "photo" varchar(180) NOT NULL,
    "short_description" varchar(240) NOT NULL,
    "description" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "brand_id" bigint NOT NULL,
    "category_id" bigint NOT NULL,
    "club_id" bigint NOT NULL,
    "supplier_id" bigint NOT NULL
);

CREATE TABLE "firstproject_orderitem" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "quantity" integer NOT NULL CHECK ("quantity" >= 0),
    "price" numeric(10, 2) NOT NULL,
    "order_id" bigint NOT NULL,
    "product_id" bigint NOT NULL
);

ALTER TABLE "firstproject_order"
    ADD CONSTRAINT "firstproject_order_customer_id_0fbcdb8c_fk_firstproj"
    FOREIGN KEY ("customer_id")
    REFERENCES "firstproject_customer" ("id")
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "firstproject_order"
    ADD CONSTRAINT "firstproject_order_user_id_e6656cc1_fk_auth_user_id"
    FOREIGN KEY ("user_id")
    REFERENCES "auth_user" ("id")
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "firstproject_product"
    ADD CONSTRAINT "firstproject_product_brand_id_cade4028_fk_firstproject_brand_id"
    FOREIGN KEY ("brand_id")
    REFERENCES "firstproject_brand" ("id")
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "firstproject_product"
    ADD CONSTRAINT "firstproject_product_category_id_78f4b082_fk_firstproj"
    FOREIGN KEY ("category_id")
    REFERENCES "firstproject_category" ("id")
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "firstproject_product"
    ADD CONSTRAINT "firstproject_product_club_id_e9246d3f_fk_firstproject_club_id"
    FOREIGN KEY ("club_id")
    REFERENCES "firstproject_club" ("id")
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "firstproject_product"
    ADD CONSTRAINT "firstproject_product_supplier_id_31e9c149_fk_firstproj"
    FOREIGN KEY ("supplier_id")
    REFERENCES "firstproject_supplier" ("id")
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "firstproject_orderitem"
    ADD CONSTRAINT "firstproject_orderit_order_id_38d1c3d0_fk_firstproj"
    FOREIGN KEY ("order_id")
    REFERENCES "firstproject_order" ("id")
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "firstproject_orderitem"
    ADD CONSTRAINT "firstproject_orderit_product_id_c2a86ba4_fk_firstproj"
    FOREIGN KEY ("product_id")
    REFERENCES "firstproject_product" ("id")
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "firstproject_category_slug_27c64e60_like"
    ON "firstproject_category" ("slug" varchar_pattern_ops);
CREATE INDEX "firstproject_customer_email_9a2ba5f6_like"
    ON "firstproject_customer" ("email" varchar_pattern_ops);
CREATE INDEX "firstproject_order_customer_id_0fbcdb8c"
    ON "firstproject_order" ("customer_id");
CREATE INDEX "firstproject_order_user_id_e6656cc1"
    ON "firstproject_order" ("user_id");
CREATE INDEX "firstproject_product_slug_06b6268d_like"
    ON "firstproject_product" ("slug" varchar_pattern_ops);
CREATE INDEX "firstproject_product_brand_id_cade4028"
    ON "firstproject_product" ("brand_id");
CREATE INDEX "firstproject_product_category_id_78f4b082"
    ON "firstproject_product" ("category_id");
CREATE INDEX "firstproject_product_club_id_e9246d3f"
    ON "firstproject_product" ("club_id");
CREATE INDEX "firstproject_product_supplier_id_31e9c149"
    ON "firstproject_product" ("supplier_id");
CREATE INDEX "firstproject_orderitem_order_id_38d1c3d0"
    ON "firstproject_orderitem" ("order_id");
CREATE INDEX "firstproject_orderitem_product_id_c2a86ba4"
    ON "firstproject_orderitem" ("product_id");

COMMIT;
